config/routes.rb
AbstractInitiative::Application.routes.draw do

  # OAUTH
  match '/users/auth/:provider/callback' => 'authentications#create'  

  authenticated :user do
    #root :to => "users#dashboard"    
  end
  root :to => 'home#index'  

  # Site stuff
  get '/about', :to => "home#about", :as => :about
  get '/404', :to => "home#404", :as => :not_found
  get '/random', :to => "home#random", :as => :random
  get '/support', :to => "home#contact", :as => :contact

  # Blog stuff
  get '/blog', :to => "blog#index", :as => :blog
  get '/blog/post', to: "blog#new", as: :new_blog  
  post '/blog/post', to: "blog#create"
  get '/blog/:month/:day/:title_slug', to: "blog#show", as: :blogpost

  # Sections
  get '/sections', :to => "sections#index", :as => :sections
  get '/section/:section_slug', to: "sections#show", as: :section

  # User account bullshit
  get '/welcome(/)', to: "home#first_login", as: "first_login"
  get '/confirming', :to => "home#confirming", :as => :confirming 
  get '/dashboard', :to => "users#dashboard", :as => :dashboard 
  devise_for :users, controllers: { confirmations: 'confirmations', registrations: 'registrations', sessions: 'sessions'}

  get '/tour(/)', to: "home#tour", as: "tour"
  put 'user/:ident', to: "users#update", as: "user_update"
  get 'users(/)', to: "users#index", as: "users"
  get 'user/:ident', to: "users#show", as: "user"
  get 'user/:ident/detail/:property', to: "users#detail", as: "user_detail"

end

app/models/user.rb
class User < ActiveRecord::Base
  require 'extensions'

  has_many :blog_posts, foreign_key: "submitter_id"
  

  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable#, :confirmable

  devise :omniauthable, :omniauth_providers => [:facebook]

  # NOTE: Disable confirming module for now!!!

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :provider, :uid, :name, :first_login, :first_name, :last_name, :url_slug, :gender, :prof_pic, :facebook_link, :location, :hometown, :bio

  validates :name, :presence => true
  
  validates_uniqueness_of :url_slug

  def active_for_authentication?
    true
  end
  
  def profile_pic
    prof_pic or "/assets/profile-placeholder.png"
  end

  def trades
    roles.dup.delete_if do |r|
      r.name == 'admin' or /mod/.match(r.name)
    end
  end


  ##############################
  #  Class methods
  ##############################
  
  def self.admins
    return with_role :admin
  end

  def self.writers
    return with_role :writing
  end

  def self.visual_artists
    return with_role :visual_art      
  end

  def self.multimedia_artists
    return with_role :multimedia
  end

  def self.musicians
    return with_role :music
  end

  ##############################
  # OmniAuth Methods
  ##############################

  def set_last_sign_in_at_to_created_at
    update_attributes({:last_sign_in_at => created_at})
  end

  def apply_omniauth(auth)
    require 'open-uri'
    
    self.uid = auth['uid']
    self.email = auth['extra']['raw_info']['email']
    [:location, :hometown].each do |field|
      begin
        assign_attributes({
          field => auth['extra']['raw_info'][field.to_s]['name']
        })
      rescue
        assign_attributes({
          field => ""
        })
      end
    end
    begin
      self.gender = auth['extra']['raw_info']['gender']
    rescue
      self.gender = "Unspecified"
    end
    self.first_name = auth['extra']['raw_info']['first_name']
    self.last_name = auth['extra']['raw_info']['last_name']
    self.name = "#{auth['extra']['raw_info']['first_name']} #{auth['extra']['raw_info']['last_name']}"
    self.facebook_link = auth['extra']['raw_info']['link']
    self.prof_pic = open("http://graph.facebook.com/#{auth['uid']}/picture?type=large&height=400&redirect=false"){|s| JSON.parse(s.readlines.first)['data']['url']}
    self.first_login = true
    # Again, saving token is optional. If you haven't created the column in authentications table, this will fail
    self.provider = auth['provider']
    self.uid = auth['uid']
    self.token = auth['credentials']['token']
    create_slug
  end

  def safe_slug
    return url_slug.to_slug unless url_slug.nil?
    return id
  end

  def create_slug
    @url_slug = (/\/[\w.]*?$/.match facebook_link).to_s.gsub(/^\//,"")
    if @url_slug.empty?
      @url_slug = name
    end
    self.url_slug = @url_slug.to_slug
  end

  def profile_pic
    prof_pic or "/assets/profile-photo-placeholder.jpg"
  end

  def url
    "/user/#{safe_slug}"
  end
    
  def edit_url
    url + "/edit"
  end

  def to_s
    "<# '#{name}'>"
  end
  
  def slugify_slug
    new_url_slug = url_slug.to_slug
    update_attribute(
                     :url_slug, new_url_slug
                     )
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
#  load_and_authorize_resource
#  skip_authorize_resource :only => [:new, :index, :show, :dashboard, :detail]
# stupid asshole cancan module doesn't work right

  def edit
    @user = current_user
  end

  def index
    @users = User.all
  end

  def show
    @detail = "profile"
    if not current_user
      flash[:alert] = "You need to sign in to view user accounts."
      redirect_to root_url
    end
    if params[:ident].to_i == 0
      @user = User.find_by_url_slug params[:ident]
    else
      @user = User.find params[:ident]
    end
    if @user.nil?
      flash[:alert] = "No such member exists."
      redirect_to root_url
    else
      @fancy_action_name = @user.name
    end
  end

  def dashboard
    if current_user.nil?
      redirect_to new_user_session_path, :alert => "You'll need to log in to view your dashboard!"
    end
  end
  
  def update
    @user = current_user
    respond_to do |format|
      if @user.update_attributes(params[:user])
        @user.slugify_slug
        if @user.first_login
          format.html { redirect_to tour_path, notice: 'Okay, thanks for the updates!' }
          format.json { head :no_content }
        else
          format.html { redirect_to user_path(@user.url_slug), notice: 'Okay, thanks for the updates!' }
        end        
      else
        format.html { redirect_to user_detail_path(current_user.safe_slug, :settings) }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
    
  def destroy
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end


  def detail    
    if params[:ident].to_i == 0
      @user = User.find_by_url_slug params[:ident]
    else
      @user = User.find params[:ident]
    end
    if params[:property] == "messages"
      if params[:m]
        @messages_tab = params[:m]
      else
        @messages_tab = "inbox"
      end
    end

    if @user != current_user and (params[:property] == "settings" or params[:property] == "messages")
      params[:property] = "profile"
    end
    if request.xhr?
      render "detail_#{params[:property]}", :layout => false
    else
      @detail = params[:property]
      @fancy_action_name = @detail.titlecase
      render "show"
    end
  end

end

app/views/users/_form.html.haml
= simple_form_for current_user, :url => "/user/#{current_user.url_slug}", :html=>{:class=>"form-horizontal"} do |f|  
  = f.input :first_name
  = f.input :last_name
  = f.input :email

  %hr/

  =f.input :location
  =f.input :hometown
  
  = f.input :gender, collection: [:male, :female, :unspecified], default: :unspecified

  =f.input :bio
  
  %hr/
  = f.input :url_slug, :label => "Custom URL:"
  .form-actions
    = f.button :submit, "Continue &rarr;".html_safe, :class => "btn btn-primary"

app/views/users/_menus.html.haml
:javascript
  $(".active").not('.breadcrumb-active').removeClass('active');
  var detail = location.href.replace(/^.*detail\//,"").replace(/\?.*$/,'');
  if(/^http:\/\//.test(detail)){
  detail = "profile";
  }
  $("a#"+detail).addClass('active');
  $("a#"+detail).parent().addClass('active');

app/views/users/_site_settings.html.haml
What kind of settings go here? Good question. Think about it.

app/views/users/_thumbnail.html.haml
.user-thumbnail
  %a.thumbnail.no-underline.username-link{:href => user_path(user), :style=>"text-align:center;"}
    %img.user-prof-pic{:src=>user.profile_pic, :alt => user.name}
    %span{:style => "display:inline-block;"}
      =user.name

app/views/users/_user.html.haml
.modal.fade{:id => "role-options-#{user.id}", :style => "display: none;"}
  .modal-dialog{:style => "left:0px;"}
    .modal-content
      = simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f|
        .modal-header
          %a.close{"data-dismiss" => "modal"} ×
          %h3 Change Roles
        .modal-body
          -if user.has_role :admin
            %p.alert.alert-success
              This user is an administrator.
          = f.input :role_ids, :collection => Role.all_except_admin, :as => :check_boxes, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids
        .modal-footer
          = f.submit "Change Roles", :class => "btn"
          %a.btn{"data-dismiss" => "modal", :href => "#"} Close

app/views/users/dashboard.html.haml
%h1
  Dashboard
  %small
    You're logged in as #{current_user.name}.
    = link_to "View your public page", current_user.url, :class => ""

.well
  %jumbotron
    %h2 About this page
    %p.lead
      Welcome to the dashboard. This page will be your landing page when you first log in, or you go to the root url as a logged-in user. Things you should be able to do from here:
    %ul
      %li View updates from artists you've followed, see who's following you
      %li Publish, promote your content
      %li View your content, see who's commented on your content, quickly update things or organize things by category
      %li View messages from other users - essentially just the inbox. Clicking on any of your messages will take you to /messages/:message_id -- none of this is implemented yet
      %li User account settings as a sub-page, maybe a tab

%p
  =link_to "Log out", destroy_user_session_path, :method => :delete

app/views/users/detail_messages.html.haml
.span12
  %h3.smallheading.text-center Your Messages
  %ul.nav.nav-tabs#messages-tab-list
    %li.active
      %a.inbox-tab-link{:href => "#inbox", :'data-toggle'=> "tab"}
        Inbox
    %li
      %a.sent-tab-link{:href => "#sent", :'data-toggle'=> "tab"}
        Sent
    %li
      %a.compose-tab-link{:href => "#compose", :'data-toggle'=> "tab"}
        Compose

  .tab-content
    .tab-pane.fade.in#inbox{:class => 'active'}
      .well
        Inbox
    .tab-pane.fade#sent
      .well
        Sent
    .tab-pane.fade#compose
      .well
        Compose
        
= render "menus"
:javascript
  $(document).ready(function() {
  $('#messages-tab-list a.#{@messages_tab}-tab-link').tab('show');
  });
      

app/views/users/detail_musician.html.haml
.jumbotron
  %p.lead
    Welcome to the musician portfolio!
    %p.alert.alert-warning
      Whoops! You don't have any audio files uploaded. (Also, there's no way to upload anything yet.)

= render "menus"

app/views/users/detail_profile.html.haml
.col-md-3
  / Friends' contests
  %h3.smallheading.text-left One category...
  %hr.smallrule/
  
.col-md-3
  / Recent contests
  %h3.smallheading.text-left Another...
  %hr.smallrule/
  %ul#recent_contests

.col-md-6
  / More
  %h3.smallheading.text-left More About #{@user.first_name}
  %hr.smallrule/
  %dl.dl-horizontal
    %dt Gender:
    %dd
      = @user.gender.titlecase or "Unspecified"
    %dt Location:
    %dd
      = @user.location or "Unspecified"
    %dt Hometown:
    %dd
      = @user.hometown or "Unspecified"
    %dt Last seen:
    %dd
      = distance_of_time_in_words_to_now @user.last_sign_in_at
      ago
    %dt Facebook link:
    %dd
      = link_to @user.facebook_link, @user.facebook_link

= render "menus"

app/views/users/detail_settings.html.haml
.col-md-12
  .container
    .row
      .col-md-7
        %h3.smallheading.text-center Website Settings
        %hr.smallrule/
        = render "site_settings"
      .col-md-5
        %h3.smallheading.text-center Profile Settings
        %hr.smallrule/
        = render "form"
  
=render "menus"

app/views/users/detail_visual_art.html.haml
.jumbotron
  %p.lead
    Welcome to the visual art portfolio!
    %p.alert.alert-warning
      Whoops! You don't have any pieces uploaded. (Also, there's no way to upload anything yet.)

= render "menus"

app/views/users/detail_writing.html.haml
.jumbotron
  %p.lead
    Welcome to the writing portfolio!
    %p.alert.alert-warning
      Whoops! You don't have anything uploaded. (Also, there's no way to upload anything yet.)

= render "menus"

app/views/users/index.html.haml
%h3 Users
.span8
  %table.table.table-condensed
    %thead
      %tr
        %th Username
        %th Email
        %th Registered
        %th Roles
        %th
        %th
    %tbody
      - @users.each do |user|
        %tr
          %td= link_to user.name, user.url
          %td= user.email
          %td= user.created_at.to_date
          %td= user.roles.map do |r| r.name.titleize end
          %td
            = render user
            %a.btn.btn-default.btn-xs{"data-toggle" => "modal", :href => "#role-options-#{user.id}", :type => "button"} Change roles...          
          %td= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user

app/views/users/show.html.haml
-title(@user.name)

.container
  .row
    .col-md-2
      /menu
      %ul.nav.nav-pills.nav-stacked
        %li.active
          %a.active.profile-view#profile{:href=>user_detail_path(@user.safe_slug, 'profile'), :"data-pjax" => "#pjax"}
            Overview
        - @user.trades.map {|r| r.name}.each do |view|
          %li
            =link_to "#{view.titlecase} Portfolio", user_detail_path(@user.safe_slug, view.gsub(/ /,"-")), :class=>"profile-view", :id=>view.gsub(/ /,'-'), :"data-pjax" => "#pjax"            
      - begin
        - if current_user == @user
          %hr/
          %h4.text-center
            Account
          %ul.nav.nav-pills.nav-stacked.logged-in-nav
            %li
              =link_to "Messages", user_detail_path(@user.safe_slug, "messages"), :class=>"profile-view", :id => "messages",:"data-pjax" => "#pjax"
            %li
              =link_to "Settings", user_detail_path(@user.safe_slug, "settings"), :class=>"profile-view", :id => "settings",:"data-pjax" => "#pjax"
      -rescue
    .col-md-3
      / profpic
      %img.img-polaroid.img-rounded#profile_pic{:src=>@user.profile_pic, :style=>"width:100%;"}
    .col-md-7
      / actions/name
      %h1.h0.text-center
        =yield(:title)
        - unless current_user == @user or current_user.nil?
          #friendship_form{:style=>"display:inline;"}
            /Friendship stuff goes here, not implemented yet
      .well.text-center
        Member for
        =distance_of_time_in_words_to_now @user.created_at
        - @user.trades.each do |t|
          &nbsp;&bullet;&nbsp;
          =t.name
      %p
        = @user.bio
        -if @user.bio.blank?
          - if @user == current_user
            You haven't written a bio yet.
            = link_to "Would you like to?", user_edit_path
          -else
            = @user.name
            has not written a bio yet.
  %hr/
  .row#pjax{:'data-pjax-container' => true}
    = render :file => "users/detail_#{@detail}"