config/routes.rb
AbstractInitiative::Application.routes.draw do

  # OAUTH
  match '/users/auth/:provider/callback' => 'authentications#create'  

  authenticated :user do
    #root :to => "users#dashboard"    
  end
  root :to => 'home#index'  

  # Site stuff
  get '/about', :to => "home#about", :as => :about
  get '/404', :to => "home#404", :as => :not_found
  get '/random', :to => "home#random", :as => :random
  get '/support', :to => "home#contact", :as => :contact

  # Blog stuff
  get '/blog', :to => "blog#index", :as => :blog
  get '/blog/post', to: "blog#new", as: :new_blog  
  post '/blog/post', to: "blog#create"
  get '/blog/:month/:day/:title_slug', to: "blog#show", as: :blogpost

  # Sections
  get '/sections', :to => "sections#index", :as => :sections
  get '/section/:section_slug', to: "sections#show", as: :section

  # User account bullshit
  get '/welcome(/)', to: "home#first_login", as: "first_login"
  get '/confirming', :to => "home#confirming", :as => :confirming 
  get '/dashboard', :to => "users#dashboard", :as => :dashboard 
  devise_for :users, controllers: { confirmations: 'confirmations', registrations: 'registrations', sessions: 'sessions'}

  get '/tour(/)', to: "home#tour", as: "tour"
  put 'user/:ident', to: "users#update", as: "user_update"
  get 'users(/)', to: "users#index", as: "users"
  get 'user/:ident', to: "users#show", as: "user"
  get 'user/:ident/detail/:property', to: "users#detail", as: "user_detail"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def tour
    current_user.update_attribute(:first_login, false)
    redirect_to root_path if current_user.nil?
  end

  def confirming    
    @conf = session[:conf]
    redirect_to root_path if flash.none?
  end

  def random
    flash[:message] = "Not a thing yet"
    redirect_to root_path
  end

  def contact
    @fancy_action_name = "Support"
  end
  
  def first_login
    @user = current_user    
    if @user.nil?
      redirect_to root_path
    else
      redirect_to user_path(@user.safe_slug) unless @user.first_login
    end
  end

  def index
    @new_blog_posts = BlogPost.first 5
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/404.html.haml
%h1 Page Not Found

%p You can stay on this page if you'd like, but there's not a lot to see here.

app/views/home/about.html.haml
about the site...

app/views/home/contact.html.haml
Contact us...

app/views/home/first_login.html.haml
-title("Welcome to Abstract Initiative!")

.container
  .row
    .col-md-3
      %img.img-polaroid.img-rounded#profile_pic{:src=>current_user.profile_pic, :style=>"width:100%;"}
    .col-md-9
      %h1
        =yield(:title)
        %small
          Customize Profile Information
      .well
        %p Your new account is almost ready, but we need you to look over the data we scraped from Facebook, just to make sure it's accurate (and to change anything, if you'd like). For now, we'll just use your facebook profile photo, but that'll change in the future.
        %p
          This data comes from
          =link_to "your public Facebook page", current_user.facebook_link
          , which you authorized when you created your account.
          =link_to "Learn more", contact_path

  .row
    .col-md-3
    .col-md-5
      = render "users/form"
    .col-md-4

app/views/home/index.html.haml
%h1 
  Abstract Initiative Pre-Alpha
%p
  Welcome to the development preview of 
  %i Abstract Initiative
  \.
  - unless current_user
    .text-center
      = link_to "Sign in with Facebook!", user_omniauth_authorize_path(:facebook), :class => "btn-lg btn-primary"
  - else
    You're signed in as #{link_to current_user.name, current_user.url}.
%hr/

%h2 New on the Blog
%hr/
-@new_blog_posts.each do |post|
  = render "blog/blogpost", :post => post

app/views/home/sections.html.haml
o

app/views/home/tour.html.haml
-title("Tour")

%h1 Someday, this will be a tour for new users!
%p This is not that day.
%p
  Click
  = link_to "here", root_url
  to continue.