config/routes.rb
AbstractInitiative::Application.routes.draw do

  # OAUTH
  match '/users/auth/:provider/callback' => 'authentications#create'  

  authenticated :user do
    #root :to => "users#dashboard"    
  end
  root :to => 'home#index'  

  # Site stuff
  get '/about', :to => "home#about", :as => :about
  get '/404', :to => "home#404", :as => :not_found
  get '/random', :to => "home#random", :as => :random
  get '/support', :to => "home#contact", :as => :contact

  # Blog stuff
  get '/blog', :to => "blog#index", :as => :blog
  get '/blog/post', to: "blog#new", as: :new_blog  
  post '/blog/post', to: "blog#create"
  get '/blog/:month/:day/:title_slug', to: "blog#show", as: :blogpost

  # Sections
  get '/sections', :to => "sections#index", :as => :sections
  get '/section/:section_slug', to: "sections#show", as: :section

  # User account bullshit
  get '/welcome(/)', to: "home#first_login", as: "first_login"
  get '/confirming', :to => "home#confirming", :as => :confirming 
  get '/dashboard', :to => "users#dashboard", :as => :dashboard 
  devise_for :users, controllers: { confirmations: 'confirmations', registrations: 'registrations', sessions: 'sessions'}

  get '/tour(/)', to: "home#tour", as: "tour"
  put 'user/:ident', to: "users#update", as: "user_update"
  get 'users(/)', to: "users#index", as: "users"
  get 'user/:ident', to: "users#show", as: "user"
  get 'user/:ident/detail/:property', to: "users#detail", as: "user_detail"

end

app/views/old/layouts/_ads.html.haml
%h4 Google Ads, for instance

.container-fluid
  - 4.times do |moot|
    .row-fluid
      %img.advertisement{:src => "/assets/placeholder.png"}
    

app/views/old/layouts/_highlight.html.haml
.container-fluid
  .row-fluid
    %h4 New Members
    -4.times do
      %img.user-prof-pic{:src => "/assets/placeholder.png"}

  .row-fluid
    %h4 Click to join!

app/views/old/layouts/_login_navbar.html.haml
%div.navbar_login
  = form_for("user", :url => new_user_session_path, :html => {:class => "navbar-form navbar-right" }) do |f|
    .form-group
      = f.text_field :email, :autofocus => true, :style => "font-size:12px;"
    .form-group
      = f.password_field :password, :style => "font-size:12px;"
    .form-group
      = f.submit "Sign in", :class => 'btn btn-primary'
    %br{:style=>"clear:both;"}
    = link_to "Forgot your password?", new_user_password_path, :class => "password_forgot navbar-right", :style => "position:relative;right:70px;"

app/views/old/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/old/layouts/_navigation.html.haml
%form.navbar-search.pull-right.hidden-phone{:style=>"position:relative;right:5px;top:10px;", :action=>"/search", :method => "get"}
  %input.col-md-2.search-query{:type=>"text", :placeholder=>"Search", :name=>"query"}
.container
  = link_to "ABSTRACT INITIATIVE", root_path, :class => 'navbar-brand', :style => "padding-bottom:20px;position:relative;top:10px;"
  %br{:style => "clear:both;"}
  %ul.list-group.list-inline
    %li.list-group-item
      = link_to 'About', about_path
    %li.list-group-item
      = link_to 'Blog', blog_path
    %li.list-group-item
      = link_to 'Artists', artists_path
    %li.list-group-item
      = link_to 'Sections', sections_path
    %li.list-group-item
      = link_to 'Random', random_path

app/views/old/layouts/_navigation_stranger.html.haml
.container
  .navbar-header
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    </button>
    = link_to "ABSTRACT INITIATIVE", root_path, :class => 'navbar-brand', :style => "padding-bottom:20px"
  .navbar-collapse.collapse
    = render "layouts/login_navbar"

app/views/old/layouts/application.html.haml
!!!
%html
  %head
    <link href='http://fonts.googleapis.com/css?family=Passion+One|Jacques+Francois|Sansita+One|Kavoon|Raleway' rel='stylesheet' type='text/css'>
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Abstract Initiative"
      %meta{:content => content_for?(:description) ? yield(:description) : "Abstract Initiative", :name => "description"}
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      = stylesheet_link_tag "application", :media => "all"
      = javascript_include_tag "application"
      = csrf_meta_tags
      = yield(:head)
  %body#all{:class => "#{controller_name} #{action_name}"}
    .navbar.navbar-inverse.navbar-static-top#navbar
      .navbar-inner
        - if true # for now, later will be "if current_user"
          = render 'layouts/navigation'
        - else
          = render 'layouts/navigation_stranger'
    #main{:role => "main"}
      .container
        .col-md-12
          .content                    
            = render 'layouts/messages'
            = yield
          %footer
      / ! end of .container
    / ! end of #main

app/views/old/layouts/stranger.html.haml
!!!
%html
  %head
    <link href='http://fonts.googleapis.com/css?family=Passion One|Jacques+Francois|Spirax|Kavoon|Raleway' rel='stylesheet' type='text/css'>
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= "Welcome to Abstract Initiative"
      %meta{:content => content_for?(:description) ? yield(:description) : "Abstract Initiative", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body#all{:class => "#{controller_name} #{action_name}"}
    .navbar.navbar-inverse.navbar-static-top#navbar
      .navbar-inner
        = render 'layouts/navigation_stranger'
    #main{:role => "main"}
      .container
        .span12
          .content                    
            = render 'layouts/messages'
            = yield
          %footer
      / ! end of .container
    / ! end of #main