config/routes.rb
AbstractInitiative::Application.routes.draw do

  # OAUTH
  match '/users/auth/:provider/callback' => 'authentications#create'  

  authenticated :user do
    #root :to => "users#dashboard"    
  end
  root :to => 'home#index'  

  # Site stuff
  get '/about', :to => "home#about", :as => :about
  get '/404', :to => "home#404", :as => :not_found
  get '/random', :to => "home#random", :as => :random
  get '/support', :to => "home#contact", :as => :contact

  # Blog stuff
  get '/blog', :to => "blog#index", :as => :blog
  get '/blog/post', to: "blog#new", as: :new_blog  
  post '/blog/post', to: "blog#create"
  get '/blog/:month/:day/:title_slug', to: "blog#show", as: :blogpost

  # Sections
  get '/sections', :to => "sections#index", :as => :sections
  get '/section/:section_slug', to: "sections#show", as: :section

  # User account bullshit
  get '/welcome(/)', to: "home#first_login", as: "first_login"
  get '/confirming', :to => "home#confirming", :as => :confirming 
  get '/dashboard', :to => "users#dashboard", :as => :dashboard 
  devise_for :users, controllers: { confirmations: 'confirmations', registrations: 'registrations', sessions: 'sessions'}

  get '/tour(/)', to: "home#tour", as: "tour"
  put 'user/:ident', to: "users#update", as: "user_update"
  get 'users(/)', to: "users#index", as: "users"
  get 'user/:ident', to: "users#show", as: "user"
  get 'user/:ident/detail/:property', to: "users#detail", as: "user_detail"

end

app/controllers/blog_controller.rb
class BlogController < ApplicationController

  def new
    @post = BlogPost.new
  end

  def create
    @post = current_user.blog_posts.build(params[:blog_post])
    if @post.save
      flash[:notice] = "Posted '#{@post.title}'."
      redirect_to @post.url
    else
      flash[:alert] = "There were some errors."
      redirect_to action: :edit
    end
  end

  def index
    @posts = BlogPost.all
  end


  def show
    if Rails.env.production?
      @post = BlogPost.where("extract(month from created_at) = ? and extract(day from created_at) = ? and title_slug = ?", params["month"], params["day"], params["title_slug"]).first
    else
      @post = BlogPost.where("strftime('%m', created_at) = ? and strftime('%d', created_at) = ? and title_slug = ?", params["month"], params["day"], params["title_slug"]).first
    end
  end

end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/blog/_blogpost.html.haml
.blogpost-container
  .blog-header
    =post.created_at.strftime("%A, %B %d, %Y")
  .blog-body
    %h1{:style=>"color:black;"} 
      =link_to post.title, post.url, class: "link-muted"
    .text-muted
      Posted by
      =link_to post.submitter.name, user_path(post.submitter.safe_slug)
      .span{:title => post.created_at, :style=>"display:inline;"}
        #{distance_of_time_in_words_to_now post.created_at} ago
    .blog-content
      =post.parse
%hr

app/views/blog/_form.html.haml
=simple_form_for @post, :url => "/blog/post", :html =>{:class=>"form-horizontal"} do |f|
  = f.input :title
  = f.input :content
  .form-actions
    = f.button :submit, "Post &rarr;".html_safe, :class => "btn btn-primary"

app/views/blog/_homepage_stranger.html.haml
%h1 Blog
- @new_posts.each do |post|
  .blog-post{:class => "post-#{post.id}"}
    %h1
      = post.title
      %small
        Posted by #{post.author} #{distance_of_time_in_words_to_now post.created_at} ago
    .blog-content
      = post.content

app/views/blog/_horizontal.html.haml
(A horizontal blog template showing the newest 5 or so entries)

app/views/blog/index.html.haml
-title("Blog")

.container
  .row
    .col-md-9
      -if current_user
        -if current_user.has_role?(:mod_blog)
          .alert.alert-info
            .h3 Blog toolbox
            %p
              You have moderator privileges to the Abstract Initiative blog.
              =link_to "New Post", new_blog_path, class: "btn btn-default"

      - @posts.each do |post|
        =render "blogpost", :post => post

    .col-md-3
      .blog-archive
        %h2.text-center.text-muted Blog Archive
        Nothing here yet...

app/views/blog/new.html.haml
-title("New Blog Post")

%h1 
  =yield(:title)

=render "form"

app/views/blog/show.html.haml
-title(@post.title)

=render "blogpost", :post => @post